export const WHEATHER_REQUEST = '@wheather/WHEATHER_REQUEST';
export const WHEATHER_SUCCESS = '@wheather/WHEATHER_SUCCESS';
export const WHEATHER_FAILURE = '@wheather/WHEATHER_FAILURE';

export const WHEATHER_LOCATION_SUCCESS = '@wheather/WHEATHER_LOCATION_SUCCESS';